[package]
name = "task_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0.140"
anyhow = "1.0.97"
dotenv = "0.15.0"
chrono = "0.4.40"